repos:
  -   repo: https://github.com/pre-commit/mirrors-pylint
      rev: 'v3.0.0a5'  # Use the sha / tag you want to point at
      hooks:
      -   id: pylint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: 'docker/algo-service.yml'
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports, --follow-imports=skip ]
        additional_dependencies: [ types-requests ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [ --profile=black ]
  - repo: https://github.com/PYCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [ "--max-line-length=120", "--ignore=W503, E203" ]

  #-   repo: local
  #    hooks:
  #    -   id: pytest-check
  #        name: pytest-check
  #        entry: pytest
  #        language: system
  #        pass_filenames: false
  #        always_run: true

exclude: '(Notebooks)/.*'
